from ev3dev.auto import INPUT_3, INPUT_4, OUTPUT_A, OUTPUT_B, OUTPUT_C, OUTPUT_D

from utils.calc.position import Position2D

ROBOT_WIDTH = 15
ROBOT_LENGTH = 23
ROBOT_HEIGHT = 16
ROBOT_WEIGHT = 0  # TODO: measure

BRICK_OFFSET_X = 0
BRICK_OFFSET_Y = -5
BRICK_POSITION = Position2D(BRICK_OFFSET_X, BRICK_OFFSET_Y, 0)

WHEEL_MOTOR_LEFT_PORT = OUTPUT_B
WHEEL_MOTOR_LEFT_DIAMETER = 4.3
WHEEL_MOTOR_LEFT_WIDTH = 2.1
WHEEL_MOTOR_LEFT_GEAR_RATIO = 1
# WHEEL_MOTOR_LEFT_GEAR_RATIO = -12 / 36
WHEEL_MOTOR_LEFT_VISUAL_ROTATION_WAY = -1
WHEEL_MOTOR_LEFT_OFFSET_X = -6.5
WHEEL_MOTOR_LEFT_POSITION = Position2D(WHEEL_MOTOR_LEFT_OFFSET_X, 0, -90)

WHEEL_MOTOR_RIGHT_PORT = OUTPUT_C
WHEEL_MOTOR_RIGHT_DIAMETER = 4.3
WHEEL_MOTOR_RIGHT_WIDTH = 2.1
WHEEL_MOTOR_RIGHT_GEAR_RATIO = 1
# WHEEL_MOTOR_RIGHT_GEAR_RATIO = -12 / 36
WHEEL_MOTOR_RIGHT_VISUAL_ROTATION_WAY = 1
WHEEL_MOTOR_RIGHT_OFFSET_X = 6.5
WHEEL_MOTOR_RIGHT_POSITION = Position2D(WHEEL_MOTOR_RIGHT_OFFSET_X, 0, 90)

SCANNER_DISTANCE_HEAD_PORT = INPUT_4
SCANNER_DISTANCE_HEAD_OFFSET_X = 0
SCANNER_DISTANCE_HEAD_OFFSET_Y = 10.5
SCANNER_DISTANCE_HEAD_POSITION = Position2D(SCANNER_DISTANCE_HEAD_OFFSET_X, SCANNER_DISTANCE_HEAD_OFFSET_Y, 0)
SCANNER_DISTANCE_PROPULSION_PORT = OUTPUT_A
SCANNER_DISTANCE_PROPULSION_GEAR_RATIO = 20 / 12
SCANNER_DISTANCE_PROPULSION_VISUAL_ROTATION_WAY = 1
SCANNER_DISTANCE_PROPULSION_POSITION = Position2D(0, 0, 0)

SCANNER_REFLECT_HEAD_PORT = INPUT_3
SCANNER_REFLECT_HEAD_OFFSET_X = 0
SCANNER_REFLECT_HEAD_OFFSET_Y = 7.5
SCANNER_REFLECT_HEAD_POSITION = Position2D(SCANNER_REFLECT_HEAD_OFFSET_X, SCANNER_REFLECT_HEAD_OFFSET_Y, 0)
SCANNER_REFLECT_PROPULSION_PORT = OUTPUT_D
SCANNER_REFLECT_PROPULSION_GEAR_RATIO = 20 / 12
SCANNER_REFLECT_PROPULSION_VISUAL_ROTATION_WAY = 1
SCANNER_REFLECT_PROPULSION_POSITION = Position2D(0, 0, 0)
