from ev3dev.auto import LargeMotor

from utils.hardware.wheel import Wheel
from utils.simulation.hardware import SimLargeMotor
from .brick import BRICK
from .hw_config import \
    WHEEL_MOTOR_LEFT_PORT, WHEEL_MOTOR_LEFT_GEAR_RATIO, WHEEL_MOTOR_LEFT_DIAMETER, \
    WHEEL_MOTOR_LEFT_WIDTH, WHEEL_MOTOR_LEFT_POSITION, \
    WHEEL_MOTOR_RIGHT_PORT, WHEEL_MOTOR_RIGHT_GEAR_RATIO, WHEEL_MOTOR_RIGHT_DIAMETER, \
    WHEEL_MOTOR_RIGHT_WIDTH, WHEEL_MOTOR_RIGHT_POSITION

sim_env = BRICK.sim_env
if sim_env is not None:
    LEFT_MOTOR = SimLargeMotor(sim_env, WHEEL_MOTOR_LEFT_PORT)
    RIGHT_MOTOR = SimLargeMotor(sim_env, WHEEL_MOTOR_RIGHT_PORT)
else:
    LEFT_MOTOR = LargeMotor(WHEEL_MOTOR_LEFT_PORT)
    RIGHT_MOTOR = LargeMotor(WHEEL_MOTOR_RIGHT_PORT)

LEFT_WHEEL = Wheel(LEFT_MOTOR, WHEEL_MOTOR_LEFT_GEAR_RATIO, WHEEL_MOTOR_LEFT_DIAMETER,
                   WHEEL_MOTOR_LEFT_WIDTH, WHEEL_MOTOR_LEFT_POSITION.x)
RIGHT_WHEEL = Wheel(RIGHT_MOTOR, WHEEL_MOTOR_RIGHT_GEAR_RATIO, WHEEL_MOTOR_RIGHT_DIAMETER,
                    WHEEL_MOTOR_RIGHT_WIDTH, WHEEL_MOTOR_RIGHT_POSITION.x)

WHEELS = [LEFT_WHEEL, RIGHT_WHEEL]
